apiVersion: v1
kind: Service
metadata:
  name: signoz-restricted
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: http-internal
      port: 8085
      targetPort: 8085
    - name: opamp-internal
      port: 4320
      targetPort: 4320
